import React from 'react'
import { connect } from 'react-redux'
import CustomBreadcrumb from '../../components/Breadcrumb'
import Categories from '../../components/Categories'
import Product from '../../components/Product'
import ProductList from '../../components/ProductList'
import Head from 'next/head';
import PageWrapper from '../../components/PageWrapper/PageWrapper'

export const index = ({ customerDetails ,storeDetails}) => {




    return (
        <>
         {/* <Head>
        <title>{storeDetails ? storeDetails?.store_name : 'Apparel Store'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={storeDetails ? storeDetails?.logo_img_url : 'favicon.ico'} />
      </Head> */}
        <div className='lg:flex lg:mt-24 md:flex '>
            {/* <CustomBreadcrumb tab="Shop" /> */}
            <Categories />
            <ProductList customerId={customerDetails?.data?.customer_id} />


        </div>
        </>
    )
}

const mapStateToProps = (state) => {
    return {
        customerDetails: state.customerDetailsReducer,
        storeDetails:state.storeDetailsReducer?.data
    }
}

const mapDispatchToProps = {}

export default connect(mapStateToProps, mapDispatchToProps)(PageWrapper(index))